# Generated by Django 4.1.6 on 2023-02-09 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('ref', '0002_page'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='page',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
